### ISSUE TITLE
Interested in making a similar app

### ISSUE THREAD

**Issue by w4rner** [clarkperkins/Attendance#1]
Can I see your app in action?

I've forked your repo. 

I see you're using Travis CI to deploy. I'm thinking of using Heroku. Are they equivalent?

Cheers,

w4rner

**Comment by clarkperkins** [comment]
Hi @w4rner, this was kind of just a throwaway project that I was playing around with when I was learning django, so it doesn't really work as far as I remember - I haven't touched it in 5-6 years though.  I don't currently have it deployed anywhere.  

But to answer your question about travis - it's not the same as heroku.  It's just a continuous integration (CI) that can automatically execute builds / run tests / deploy artifacts to a repository / etc.  It can't actually run your web server like heroku does.
